// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    ignores: [
      "dist/*",
      // Generated by expo-router; carries its own disable directives.
      ".expo/*",
      // Deno, not Node: `jsr:`/`npm:` specifiers are unresolvable here, and
      // tsconfig.json excludes them for the same reason. Type-checking the
      // edge functions is a separate job for `deno check`.
      "supabase/functions/*",
    ],
  }
]);
